language: python
python:
- '3.6'
script:
- pytest test
install:
- pip install click
- pip install -r requirements.txt
deploy:
  provider: pypi
  user: ddorn
  password:
    secure: dzZ6V66P9fdUg2Gx7f5VyiQFqFhnU+ypsQysixGUkIskP19t7+1Kkh+L4EgjpvL2sRyr3MRNGAxfSqDf9e2xqitnHOQ9paspRLCtxcrXvAFCTKWAnGsqP1gpNnrJw2e/Ed7TffBpfhtjXdoa2m4r/GiWmT+YwNt0kZ6Fcl91pnctaql2NyOFiQ2yKfETbRAi9IGAQxwJ1ETG4WL2190f7B60+BISU+BVHcVpiZ3B/KZtzfhbSi/NH/LHMZKs43uVftpElNlj/srUDkpNvM3JfS7p+VIA2onbnMn5ntbcg413kusniAI9NhrEgm3qZARhXrsr+GImZKKEw521MveCmWR4cJhc0xq0Ei9rduLE1ClyD8yK4gpUEPuG9ignEWp6ALEQbijOnAytomugbwf8rCrBEkoto22X5x7q8SV16fud9/2VKtqnK9b/vbr7mOBqu/L+ftK/HA1eT2TrGPxfA6C6kGpcADQ2XTSCQOddP04l6z+aHEOQJhkT2Y1yKgsZMKyf1D7fmOSYsjT0vKpi6THJ0BS3CCoJlX1Ki+enS+tP8qtqdk0rElRDEihlovIKKUJbbPHW6bvGY19+sm5v5tj/S1+WZOHB1JY7SHKT/gx8IGFuAYuJlx9s0CTP8g6QIDc9O2JoVilJ5vpxZawWIeaTrfwONq2B/HGAFet/BDo=
  on:
    condition: $TRAVIS_PYTHON_VERSION = "3.6"
    tags: true
notifications:
  slack:
    secure: eMh5OqS6clMXFsrZnM+DSUgKl2vIQ5/kq6/jp3578xTTNFic3LmhDOvHw/ek3bmIy57g9ReiytBa+LXsZFNLXbB+72XH9iswgePrqkfRpnpfNHUsJFVaF1jQNu58ZpPq7ecDnJOShuuiKkFNLtLFS6Syhw448LywFAZvh/neeRiOHMHI95A1W8bpBrn/P5UdzGasi8hEB313s06vrH3Pvls/aaSmKxWZjyK0xgTgeb5vR8rvawnEgTM1SIeDsdxumYKSkpvSocBPe3hvSHtVkN+xC45qpxD7uLhDgWvKpATfHuvyS2H784QT+sC4Bd9qNWdTmpdwsLEj/wXkk2PbkWnjxByRSvwNdTuflp6S1fP2JTTwgnLvSN6JiGrFMbfQN7pouk5Q7Z7K1Yyx552Lg31f3B7u4RsKHGao3GJtLq70jzI/G/lkUetpF0dszCAdHxBa+pNRIV3ybb/oNkVfzZRX8QIk42ahstzCY05LmZ1bfaOC1nL8Z1JOkzQ9MIeM0qvtIoECUHLjnmJOY6AKCB6+UK8REy+LjnP6y4NH2MgRM6vaBLu9OkFGx2Ct53jbv70Lp512dWU6HFQuVs4P8dmRLU2a49HyO9h06vwCo2OdQVrY3zrVHwQkDVqUJOcuyFzg9cKX8wDqmlnMH1rZHhimDEZKm/ry5hCmdKS5JAE=
