language: python
python:
- '3.6'
script:
- pytest test
install:
- pip install click
- pip install -r requirements.txt
deploy:
  provider: pypi
  user: ddorn
  password:
    secure: dzZ6V66P9fdUg2Gx7f5VyiQFqFhnU+ypsQysixGUkIskP19t7+1Kkh+L4EgjpvL2sRyr3MRNGAxfSqDf9e2xqitnHOQ9paspRLCtxcrXvAFCTKWAnGsqP1gpNnrJw2e/Ed7TffBpfhtjXdoa2m4r/GiWmT+YwNt0kZ6Fcl91pnctaql2NyOFiQ2yKfETbRAi9IGAQxwJ1ETG4WL2190f7B60+BISU+BVHcVpiZ3B/KZtzfhbSi/NH/LHMZKs43uVftpElNlj/srUDkpNvM3JfS7p+VIA2onbnMn5ntbcg413kusniAI9NhrEgm3qZARhXrsr+GImZKKEw521MveCmWR4cJhc0xq0Ei9rduLE1ClyD8yK4gpUEPuG9ignEWp6ALEQbijOnAytomugbwf8rCrBEkoto22X5x7q8SV16fud9/2VKtqnK9b/vbr7mOBqu/L+ftK/HA1eT2TrGPxfA6C6kGpcADQ2XTSCQOddP04l6z+aHEOQJhkT2Y1yKgsZMKyf1D7fmOSYsjT0vKpi6THJ0BS3CCoJlX1Ki+enS+tP8qtqdk0rElRDEihlovIKKUJbbPHW6bvGY19+sm5v5tj/S1+WZOHB1JY7SHKT/gx8IGFuAYuJlx9s0CTP8g6QIDc9O2JoVilJ5vpxZawWIeaTrfwONq2B/HGAFet/BDo=
  on:
    condition: $TRAVIS_PYTHON_VERSION = "3.6"
    tags: true
notifications:
  slack:
    secure: Wa2iQMPDWstmis6+C8xD0LiWdTSM36syzbxTLCc8dnADgQJRS6rS5nXvytvYtdT7E2jBGYq/uo7Xgog6Oqyq1VSfmmtjg2g0JVfULD2LXaYnAiq1U541dRMnQq5MdE/3Qi6bSs/Eqlwn1duVCCoT8KOnD6HoKdSvu16xaeGQINX3qKut5UMRb7GI/EYlt4948PMsrdiiTiWX4yC9yGUdYloAx9a5xlE6TNHB8jmc2MX4ASwyJhz7CStwzRmF3AXKgzq8+CSN6h1CYTma+0l/Lwf7mFCkCXGwkfrTYga5kZSKsYN3pzIbX7jbDizieteNnuIfuqJrJhNb0QB7vCPoHuwJDCFygBzjeDImWZuxi4lVdFfWwSQq3j/0VoOyJhW6p0XcbxQNLLL7An6dVeXMxQX7qMQynNchfFJ7tDUwcQej2f96kdi8OIo8ERzQ2xctBtP1d7hCV9JE/anbssW5KvzRYygTKOLHEAlr4Nsw4HRYaP1PTGFYDAr9hro+Y0FIivDp6P/lEhCxuHd4b8yI2CS8RL4GjH3+fDplW6252KP5wzkVIEZ7y9B9eSYfuB3SBeX7r5scFLGxIVaqadp+e2wFLlI7UYM3lsXPwZg5y7eypGRsbTP8qLjw4XsOA1ZAXH9+ZhxVtWXlgRXocmEibzgjuzYOgbzfgYlWcNMthbY=
