try:
    from manconfig import ManConfig
except ModuleNotFoundError:
    from man.manconfig import ManConfig


def manifest(config: ManConfig):
    # we cont want the precompiled flags
    manif = [
        '# THIS FILE IS AUTOMATICALLY GENERATED. IT IS POINTLESS TO MODIFY IT',
        '',
        'global-exclude *.py[co]'
    ]

    # we includ all packages and everything under them
    for package in config.packages:
        manif.append('graft %s' % package)

    with open('MANIFEST.in', 'w') as f:
        f.write('\n'.join(manif))

def setup(config: ManConfig):
    pass

def requirements(config: ManConfig):
    pass
